### ISSUE TITLE
IC卡在特定角度下点击闸机会出现请去客服中心的提示

### ISSUE THREAD

**Issue by kjbkshuyiGithub** [DoveCotMC/Metropolis#6]
使用版本：0.2.0BETA 1.19.2 NTE+MTR3

![image](https://github.com/user-attachments/assets/1f6e283d-2104-4e64-8d6f-0e370b69192f)

差不多是以上这个角度，而且这样提示出现一次后在一定时间内都不能使用IC卡了。

**Comment by Arrokoth486958** [comment]
我怀疑你是不是点到旁边闸机去了？
这个算是mc的问题了，有的时候碰撞箱大于一个方块的时候就没法选中

**Comment by kjbkshuyiGithub** [comment]
大概不是，就一个闸机

**Comment by Arrokoth486958** [comment]
点到隔壁方块

**Comment by Arrokoth486958** [comment]
我看你选中的碰撞箱不对

**Comment by kjbkshuyiGithub** [comment]
eaz
