### ISSUE TITLE
Possible port to forge/1.20.1

### ISSUE THREAD

**Issue by Diopptazz** [DoveCotMC/Metropolis#7]
Hello, 
I love the turnstiles and the independent ticket/IC Card System. I would like to use those alongside the create mod. Unfortunately, the server I am on uses forge and is on the 1.20.1 mod. I also lack the java knowledge to port it myself. Would it be a possibility for a port to be made to that version anytime soon (At least of the ticket/card system and the turnstiles) ?

**Comment by kjbkshuyiGithub** [comment]
At the moment, there should only be FABIRC

**Comment by Arrokoth486958** [comment]
No, we only make Fabric versions.
